# -*- coding: utf-8 -*-
"""average(while!1000).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18YotPp490SjWqg4xQ-eWdAklHwO559n6
"""

def Mean():
  counter = 0
  sum = 0
  while i!=1000:
    i = int(input())
    sum+=i
    counter+=1
  return (sum-1000)/(counter-1)
