# -*- coding: utf-8 -*-
"""average100.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yv0kd9GloVOKgVWKjTp-FImiklE0OUOX
"""

def mean():
  s=0
  for i in range(100):
    s+=int(input())
  return s/100.0
