# -*- coding: utf-8 -*-
"""class(1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g3Wcpv3PnpTeK5pAnC52e_h5zvD960cr
"""

class person:
  name=none
  score=100
  def say_hello(self):
    print("hello")
